telegram:
  token: 5089864236:AAE2lbvo2NxUt5zTl-8GWQQ0E7qLFLdPwsI      # Telegram bot tokens look like this: 113031530:AAH_4c5Gt9gsVu82OVNjUV7poU7PodYiNsA
  useFirstNameInsteadOfUsername: false
  colonAfterSenderName: false
  skipOldMessages: true
  sendEmojiWithStickers: true
discord:
  useNickname: false
  token: OTE4NTU1MTAyMjQyMDQ1OTUy.YbI9Gg.V5q-Ks4LYYbNUY4yW3zwyZSNYnc   # Discord bot tokens look like this: MjI3MDA1NzIvOBQ2MzAzMiMz.DRf-aw.N0MVYtDxXYPSQew4g2TPqvQve2c
  skipOldMessages: true
  replyLength: 100
  maxReplyLines: 2
bridges:
  - name: First bridge
    direction: d2t
    telegram:
      chatId:  -1001087147443  # Remember that Telegram group and channel IDs are negative. Include the `-` if you are bridging a group or a channel
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: true
      relayCommands: true
      crossDeleteOnDiscord: true
    discord:
      channelId: '918548492941656085'     # This ID must be wrapped in single quotes. Example: '244791815503347712'
      relayJoinMessages: false
      relayLeaveMessages: false
      sendUsernames: false
      crossDeleteOnTelegram: true
debug: false
